POST http://localhost:9080/jee-demos/api/users
Content-Type: application/json

{
  "lastName": "Janssens",
  "firstName": "Bram",
  "username": "admin",
  "password": "admin",
  "roles": [
    "ADMIN"
  ]
}

###

POST http://localhost:9080/jee-demos/api/users
Content-Type: application/json

{
  "lastName": "Janssens2",
  "firstName": "Bram2",
  "username": "user2",
  "password": "user",
  "roles": [
    "USER"
  ]
}

###

POST http://localhost:9080/jee-demos/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

###

GET http://localhost:9080/jee-demos/api/beers
Authorization: Bearer {{auth_token}}


###

GET http://localhost:9080/jee-demos/api/beers/1
Authorization: Bearer {{auth_token}}

###

POST http://localhost:9080/jee-demos/api/beers
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "alc": 9.0,
  "brand": "Bram",
  "fillLevel": 100
}

###

POST http://localhost:9080/jee-demos/api/beers/ejb
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "alc": 9.0,
  "brand": "Bram",
  "fillLevel": 100
}